name: VirtualAssistant
favicon: null
layout_spectrum: 0.75181
typography_spectrum: 0.24819
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a79c9a'
    - '#191814'
    - '#74675e'
    - '#5b322c'
    - '#af7e6d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
