name: VirtualAssistant
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e5533'
    - '#fffffd'
    - '#7a826b'
    - '#ccc38a'
    - '#ebe3b4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
