typography_spectrum: 0.24819
color:
  brandColors:
    - '#a79c9a'
    - '#191814'
    - '#74675e'
    - '#5b322c'
    - '#af7e6d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74819
analytics:
  google: UA-74098200-1
  facebook: null
  twitter: null
name: TheVirtualAssistant
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'RATES:'
    id: 5fb3e8a5-4128-42dc-8502-9bd7cf55aac4
    type: content
  - name: 'CONTACT:'
    id: bcc7b8ee-ed71-4956-b2cd-16af89fd21e3
    type: content
  - name: WHO NEEDS ME?
    id: 1431b690-6b7a-4641-b39e-cf866cf1559d
    type: content
  - name: 'Qualifications:'
    id: c6d3c367-b6f2-4075-a223-5705131a9e41
    type: content
favicon: null
title: ''
description: ''
purpose: []
